### ISSUE TITLE
공감 버튼을 눌렀을 때, count 변화 구현

### ISSUE THREAD

**Issue by xqqldir** [Likelion12-KNU/your-apartment-frontend#2]
## 필요한 기능
- 공감 버튼 비활성화 상태에서 클릭 시 +1
- 공감 버튼 활성화 상태에서 클릭 시 -1

## 해야 할 일 
- [x] 비활성화 상태에서 클릭 시 +1
- [x] 활성화 상태에서 클릭 시 -1
- [x] 페이지 로드 시 초기화되어 다시 버튼 활성화

**Comment by Kim-jaeyeon** [comment]
확인하였습니다!
